"""replace unique constraints with partial unique indexes

Revision ID: 2bed535ff0b0
Revises: 3316319316a8
Create Date: 2026-05-23 19:51:26.293797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2bed535ff0b0"
down_revision: Union[str, Sequence[str], None] = "3316319316a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("boards_name_key"), "boards", type_="unique")
    op.drop_constraint(op.f("boards_slug_key"), "boards", type_="unique")
    op.create_index(
        "uq_boards_name",
        "boards",
        ["name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_boards_slug",
        "boards",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.create_index(
        "uq_users_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_users_username",
        "users",
        ["username"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_users_username",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_users_email",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("users_username_key"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(
        "uq_boards_slug",
        table_name="boards",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_boards_name",
        table_name="boards",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        op.f("boards_slug_key"), "boards", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("boards_name_key"), "boards", ["name"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
