"""add_post_comment_count

Revision ID: 9fe49ab15048
Revises: e1c912af7df6
Create Date: 2026-05-26 21:12:35.892109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9fe49ab15048"
down_revision: Union[str, Sequence[str], None] = "e1c912af7df6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "posts",
        sa.Column("comment_count", sa.BigInteger(), nullable=False, server_default="0"),
    )
    op.alter_column("posts", "comment_count", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "comment_count")
    # ### end Alembic commands ###
